# 1-4. throws문 & 예외 처리 패턴


## ✏️  예외처리 방법

- 발생한 예외를 try-catch문을 사용해 명시적으로 즉각 처리한다 : [명시적 예외처리](1-1%20%E1%84%86%E1%85%A7%E1%86%BC%E1%84%89%E1%85%B5%E1%84%8C%E1%85%A5%E1%86%A8%20%E1%84%8B%E1%85%A8%E1%84%8B%E1%85%AC%E1%84%8E%E1%85%A5%E1%84%85%E1%85%B5%200a204648bd7444d5842fbd6d74d2b934.md)
- 즉각적으로 처리하지 않고 발생한 예외를 던진다 : throws문

## ✏️  throws문 사용하기

```java
public void readFile(String filename) **throws FileNotFoundException, IOException** {		
	FileReader fr = null; 			
	fr = new FileReader(filename);	
}
```

- throws문을 사용하면 예외를 해결한 것이 아닌, 예외를 던진 것이므로 **메소드를 호출한 곳으로 예외가 던져진다.**
- 하나의 예외만을 던질 수 있는 것은 아니며, 여러개의 예외를 한번에 던질 수 있다
- 이 때, 부모 자식관계의 예외라면 부모 예외만을 던져도 자식 예외를 대응할 수 있다

```java
public class CompileTest3 {
	// main 메소드를 호출한 곳 = JVM 으로 예외를 던진다 : JVM에서 자동으로 던져진 예외를 처리한다
	public static void main(String[] args) **throws FileNotFoundException**  {
		FileReading3 fr = new FileReading3();
		String path = "/Users/muje/Desktop/dev/학원/miracom_edu/util/messag.txt";
		fr.readFile(path);		
		System.out.println("파일을 잘 읽어들였습니다..");
	}
}
```

- main method에서 예외를 던지게 되면, 메인 메소드가 호출된 곳인 JVM으로 예외를 던지게되고 예외를 JVM이 처리한다
- throws문을 사용하면 Stream을 close해주는 finally문을 작성할 수 없다는 문제가 발생한다
- finally문은 try문과 반드시 함께 사용되어야하므로 throws문을 사용한 경우, finally문을 사용할 수 없다
- 즉, 사용된 자원을 닫기 위한 finally 문을 사용할 수 없다

## ✏️  예외 처리 패턴

```java
package exception.compile.test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

class FileReading{
										// readFile 메소드를 호출한 곳으로 예외를 던진다 
	public void readFile(String filename) **throws IOException** {		
		
		FileReader fr = null; 			
		
		**try {
			fr = new FileReader(filename);	
		}finally{
			fr.close();
		}**
			
		System.out.println("FileReader  Creating...");					
		System.out.println("file....end...");		
	}//readFile
}//class

public class CompileTest3 {
	public static void main(String[] args) {
		FileReading fr = new FileReading();
		String path = "/Users/muje/Desktop/dev/학원/miracom_edu/util/message.txt";
		**try {
			fr.readFile(path);
		} catch (FileNotFoundException e) {			
		} catch (IOException e) {			
		}**		
		System.out.println("파일을 잘 읽어들였습니다..");
	}
}
```

- 그렇기 때문에 아래와 같은 패턴을 가지게 된다
    1. Vo 클래스에서 선언된 메서드 내부에서 발생한 throws문을 사용해 메인 메서드로 던진다 
        - catch문은 작성하지 않고 throws문을 사용해 던진다
    2. 자원을 닫기 위한 finally문은 반드시 작성되어야 하기때문에 try-fiinally 의 형태로 작성한다  (catch문은 throws)
    3. Test클래스의 메인 메서드에서는 명시적으로 try-catch 구문을 통해 예외처리를 한다